### ISSUE TITLE
Run tests on CircleCI

### ISSUE THREAD

**Issue by reginafcompton** [GIIMSC/goodwilldatainitiative-etl#1]
```
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            export SLUGIFY_USES_TEXT_UNIDECODE=yes
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "goodwilldatainitiative-etl/setup.py" }}

      # Run (pytest) tests.
      # https://pytest.org
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd goodwilldatainitiative-etl/
            python -m pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports
```
